version: '3'

services:
  memcached:
    image: memcached:latest
    ports: 
      - '11211:11211' 
  db:
    image: mysql:5.7
    ports:
      - '3302:3306'
    environment:
       MYSQL_DATABASE: 'db_master'
       MYSQL_USER: 'db_user'
       MYSQL_PASSWORD: 'Pass.1234'
       MYSQL_ROOT_PASSWORD: 'Pas.1234'
       MYSQL_HOST: 'localhost'
       MYSQL_PORT: '3306'
    volumes:
      - .setup.sql:/docker-entrypoint-initbd.d/setup.sql

  web:
    build: .

    command: python manage.py runserver 0.0.0.0:8000
     
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
